[package]
name = "candle-crf"
version = "0.7.2"
edition = "2021"
description = "porting pytorch-crf to candle"
readme = "README.md"
repository = "https://github.com/kigichang/candle-crf"
license = "MIT"
license-file = "LICENSE"
keywords = ["candle", "crf", "conditional random field", "pytorch"]

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle" }
candle-nn = { git = "https://github.com/huggingface/candle" }

[dev-dependencies]
itertools = "0.13.0"
tuple-conv = "1.0.1"
