[package]
name = "candle-crf"
version = "0.8.3"
edition = "2021"
description = "porting pytorch-crf to candle"
readme = "README.md"
repository = "https://github.com/kigichang/candle-crf"
license-file = "LICENSE"
keywords = ["candle", "crf", "pytorch"]

[dependencies]
accelerate-src = { workspace = true, optional = true }
intel-mkl-src = { workspace = true, optional = true }
candle-core = { workspace = true }
candle-nn = { workspace = true }


[dev-dependencies]
itertools = "0.13.0"
tuple-conv = "1.0.1"

[features]
default = []
accelerate = ["dep:accelerate-src", "candle-core/accelerate", "candle-nn/accelerate"]
mkl = ["dep:intel-mkl-src", "candle-core/mkl", "candle-nn/mkl"]